export const movieList = [
  { title: "The Matrix", rating: 7.5, category: "Action" },
  { title: "Focus", rating: 6.9, category: "Comedy" },
  { title: "The Lazarus Effect", rating: 6.4, category: "Thriller" },
  { title: "Everly", rating: 5.0, category: "Action" },
  { title: "Inception", rating: 8.8, category: "Sci-Fi" },
  { title: "The Shawshank Redemption", rating: 9.3, category: "Drama" },
  { title: "Pulp Fiction", rating: 8.9, category: "Crime" },
  { title: "The Dark Knight", rating: 9.0, category: "Action" },
  { title: "Interstellar", rating: 8.6, category: "Sci-Fi" },
  { title: "The Godfather", rating: 9.2, category: "Crime" },
  { title: "Titanic", rating: 7.8, category: "Romance" },
  { title: "Avatar", rating: 7.8, category: "Sci-Fi" },
  { title: "Jurassic Park", rating: 8.1, category: "Adventure" },
  { title: "Gladiator", rating: 8.5, category: "Action" },
  { title: "Forrest Gump", rating: 8.8, category: "Drama" },
  { title: "The Silence of the Lambs", rating: 8.6, category: "Thriller" },
  { title: "The Departed", rating: 8.5, category: "Crime" },
  { title: "The Avengers", rating: 8.0, category: "Action" },
  { title: "The Social Network", rating: 7.7, category: "Drama" },
  { title: "The Lion King", rating: 8.5, category: "Animation" },
  { title: "Parasite", rating: 8.6, category: "Thriller" },
  { title: "Whiplash", rating: 8.5, category: "Drama" },
  { title: "The Grand Budapest Hotel", rating: 8.1, category: "Comedy" },
  { title: "Mad Max: Fury Road", rating: 8.1, category: "Action" },
  { title: "Joker", rating: 8.4, category: "Crime" },
  { title: "La La Land", rating: 8.0, category: "Romance" },
  { title: "Moonlight", rating: 7.4, category: "Drama" },
  { title: "Get Out", rating: 7.7, category: "Horror" },
  { title: "Her", rating: 8.0, category: "Romance" },
  { title: "Blade Runner 2049", rating: 8.0, category: "Sci-Fi" }
];
